
version: '3'

services:
  backend:
    env_file:
        "./be/.env"
    build:
      context: ./be
      dockerfile: ./Dockerfile
    ports:
      - "3001:3001"
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "backend:be"